### ISSUE TITLE
Trust iOS failed to check personal_sign

### ISSUE THREAD

**Issue by hamberluo** [trustwallet/trust-web3-provider#340]
here is a trust ios connect wallet bug feedback with wallet connect protocol
trust ios failed to check personal_sign ecRecover
while trust android is success

**Comment by hewigovens** [comment]
Which dapp did you test?

**Comment by hamberluo** [comment]
> Which dapp did you test?

You can goto https://pro.apex.exchange/trade/ETH-USDC
1. click connect button
2. select walletconnect
3. use Trust iOS to scan qr code

then you can reproduce that bug.
compare with other wallets like metamask.

**Comment by hewigovens** [comment]
Thanks for the report, forwarded to the team

**Comment by Daniel-Judg** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by hamberluo** [comment]
any update? @hewigovens

**Comment by hewigovens** [comment]
Fixed in the code, wait for Apple review

**Comment by hamberluo** [comment]
android also has a bug @hewigovens 

this is deep link docs
# For deep links
examplewallet://wc?uri=wc:00e46b69-d0cc-4b3e-b6a2-cee442f97188@1?bridge=https%3A%2F%2Fbridge.walletconnect.org&key=91303dedf64285cbbaf9120f6e9d160a5c8aa3deb67017a3874cd272323f48ae

# For universal links
https://example.wallet/wc?uri=wc:00e46b69-d0cc-4b3e-b6a2-cee442f97188@1?bridge=https%3A%2F%2Fbridge.walletconnect.org&key=91303dedf64285cbbaf9120f6e9d160a5c8aa3deb67017a3874cd272323f48ae

trust android proccess endoded queries but other wallets dont do that.

**Comment by vcoolish** [comment]
> android also has a bug @hewigovens
> 
> this is deep link docs
> 
> # For deep links
> examplewallet://wc?uri=wc:00e46b69-d0cc-4b3e-b6a2-cee442f97188@1?bridge=https%3A%2F%2Fbridge.walletconnect.org&key=91303dedf64285cbbaf9120f6e9d160a5c8aa3deb67017a3874cd272323f48ae
> 
> trust android proccess endoded queries but other wallets dont do that.

what's the problem with handling encoded links?

**Comment by hamberluo** [comment]
> > android also has a bug @hewigovens
> > this is deep link docs
> > # For deep links
> > examplewallet://wc?uri=wc:00e46b69-d0cc-4b3e-b6a2-cee442f97188@1?bridge=https%3A%2F%2Fbridge.walletconnect.org&key=91303dedf64285cbbaf9120f6e9d160a5c8aa3deb67017a3874cd272323f48ae
> > trust android proccess endoded queries but other wallets dont do that.
> 
> what's the problem with handling encoded links?

walletconnect docs mentioned,
we should not use url encode in deeplink

but trust android only accept this as deeplink:
trust://wc?uri=wc%3Aad2054ac-1244-4a24-83c9-16aef547c44f%401%3Fbridge%3Dhttps%253A%252F%252Fj.bridge.walletconnect.org%26key%3Dd26f3caaae657a2d228f66045ccebc8dc7a4b0eb1ca43eff984c03da74410f13

**Comment by hamberluo** [comment]
> Fixed in the code, wait for Apple review

we tested trust ios 7.22.
it still failed to connect while other wallets succeeded.

You can goto https://pro.apex.exchange/trade/ETH-USDC

click connect button
select walletconnect
use Trust iOS to scan qr code
then you can reproduce that bug.
compare with other wallets like metamask.

in which version do you fix? not 7.22?
@hewigovens

**Comment by SUPPORTTEAMHERR** [comment]
> here is a trust ios connect wallet bug feedback with wallet connect protocol
> trust ios failed to check personal_sign ecRecover
> while trust android is success

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by SUPPORTTEAMHERR** [comment]
> android also has a bug @hewigovens 
> 
> this is deep link docs
> # For deep links
> examplewallet://wc?uri=wc:00e46b69-d0cc-4b3e-b6a2-cee442f97188@1?bridge=https%3A%2F%2Fbridge.walletconnect.org&key=91303dedf64285cbbaf9120f6e9d160a5c8aa3deb67017a3874cd272323f48ae
> 
> trust android proccess endoded queries but other wallets dont do that.

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by WalletSupportt** [comment]
> here is a trust ios connect wallet bug feedback with wallet connect protocol
> trust ios failed to check personal_sign ecRecover
> while trust android is success

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by ArtemGoryunov** [comment]
@hamberluo 7.23 version should work

**Comment by hamberluo** [comment]
> @hamberluo 7.23 version should work

this issue closed, but another issue here.
https://github.com/trustwallet/trust-web3-provider/issues/352
